# Use a base image with Android SDK and required dependencies
FROM openjdk:8-jdk-slim

# Set environment variables
ENV ANDROID_COMPILE_SDK="31" \
    ANDROID_BUILD_TOOLS="31.0.0" \
    ANDROID_SDK_TOOLS="7583922" \
    ANDROID_HOME="/sdk"

# Install Android SDK
RUN mkdir "$ANDROID_HOME" .android \
    && cd "$ANDROID_HOME" \
    && wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip -O sdk-tools.zip \
    && unzip -q sdk-tools.zip \
    && rm sdk-tools.zip

# Add Android SDK tools to PATH
ENV PATH="$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"

# Accept licenses
RUN yes | sdkmanager --licenses

# Install required Android SDK components
RUN sdkmanager --update \
    && sdkmanager --install "platforms;android-$ANDROID_COMPILE_SDK" \
    && sdkmanager --install "build-tools;$ANDROID_BUILD_TOOLS"

# Copy your Android project files into the Docker image
COPY . /app

# Set working directory
WORKDIR /app

# Build the Android project
RUN ./gradlew assembleDebug

# Entry point command to run your application
CMD ["./gradlew", "assembleRelease"]
